### ISSUE TITLE
Does it make sense to schedule events on a threadpool?

### ISSUE THREAD

**Issue by posix4e** [dwrensha/gj#1]

**Comment by dwrensha** [comment]
As things currently stand, scheduling events on a thread pool would not be possible because event callbacks are not required to be `Send`.

I've added some documentation since you filed this. Do you think I make things sufficiently clear in [this example](https://github.com/dwrensha/gj/blob/master/examples/threads.rs) and [this post](http://dwrensha.github.io/capnproto-rust/2015/05/25/asynchronous-io-with-promises.html)?
